# Generated by Django 5.0.6 on 2024-07-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
